//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunityList
    {
        public int no { get; set; }
        public System.DateTime date_added { get; set; }
        public int entered_by { get; set; }
        public string description { get; set; }
        public string counter_measure { get; set; }
        public int person_responsible { get; set; }
        public System.DateTime due_date { get; set; }
        public int completion_porcent { get; set; }
        public int is_completed { get; set; }
    
        public virtual User User { get; set; }
    }
}
